services:
    portainer-nginx:
        container_name: portainer-nginx
        image: nginx:${NGINX_VERSION}
        restart: unless-stopped
        volumes:
            - ./nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        depends_on:
            - portainer-portainer
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOST}
            SELF_SIGNED_HOST: ${SELF_SIGNED_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOST}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - portainer

    portainer-portainer:
        container_name: portainer-portainer
        image: portainer/portainer-ce:${PORTAINER_VERSION}
        restart: unless-stopped
        volumes:
            - ../data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - portainer

networks:
    portainer:
    nginx-proxy:
        external: true
